### ISSUE TITLE
Cant start a game with this plugin

### ISSUE THREAD

**Issue by TheBricktop** [uFrame/ECS#3]
Displays This error:

Assets/Plugins/uFrame/UniRx/Examples/Sample11_Logger.cs(12,25): error CS0104: `Logger' is an ambiguous reference between `UniRx.Diagnostics.Logger' and `UnityEngine.Logger'

**Comment by jjjuande** [comment]
The error is located on a UniRx example file, so you should change Logger to UniRx.Diagnostics.Logger on the error line. (Another solution is to delete the entire Assets/Plugins/uFrame/UniRx/Examples folder)

**Comment by ZimM-LostPolygon** [comment]
I never imported the examples folder in the first place. The only thing you need is `Assets/Plugins/UniRx/Scripts`.
