### ISSUE TITLE
uFrame.Attributes not found in the content [Resolved]

### ISSUE THREAD

**Issue by 3DMagicVR** [uFrame/ECS#6]
Hello there, I got here because I download the uFrame.ECS and when I wan to to use it, the console drops 152 errors, almost all of them are about the missing assembly reference "uFrame.Attributes", I search for it but nothing to be appears, there's not included or I miss something?, thanks for your attention.

**Comment by jjjuande** [comment]
For uFrame.ECS to work you need to download also:

- uFrame.Designer (Core)

- uFrame.Kernel. 

And UniRx from the Unity Asset Store.

Just download this file: [uFrameECS.zip](https://github.com/uFrame/uFrame.ECS/files/1517596/uFrameECS.zip)
And unzip it into the Assets folder of a new Unity project. There are a few warnings, but it seem to be working properly. (This should give you an idea on where to put everything on the project)

Sadly, the provided ECS example project freezes when trying to take a look at the graphs: https://github.com/uFrame/uFrame.ECS/raw/master/uFrame.ECS/Examples/uFrameECSExample.unitypackage

**Comment by jjjuande** [comment]
Then take a look to the ECS example: https://github.com/uFrame/uFrame.ECS/raw/master/uFrame.ECS/Examples/uFrameECSExample.unitypackage

**Comment by 3DMagicVR** [comment]
Hey thanks, that was quick.
